FROM ubuntu:22.04
RUN apt-get update && apt-get install -y curl git
RUN curl -L https://foundry.paradigm.xyz/ | bash
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
